### ISSUE TITLE
Open Source Updates?

### ISSUE THREAD

**Issue by cs16lover** [mailsac/mailsac-examples#3]
Hello,

I've found out that open source repository for mailsac.com project is outdated.

Will you update the source code of mailsac.com as open source?

Thanks

**Comment by ruffrey** [comment]
Thanks - the goal is to update things eventually but we don't have any dates. The project was split into microservices to deal with scaling, and we didn't keep the main public repo up to date. A lot of our library code is open source now, or will be.
